from filesdsl import execute_fdsl

code = """
docs = Directory("data")
print("=== DIRECTORY TREE (depth=2) ===")
print(docs.tree(max_depth=2, max_entries=120))

print("=== PDF TEST ===")
pdf = File("data/another_folder/2405.00332v3.pdf")
print("contains(model):", pdf.contains("model", ignore_case=true))
print("search(model):", pdf.search("model", ignore_case=true))
print("head_len:", len(pdf.head()))
print("tail_len:", len(pdf.tail()))
print("table:")
print(pdf.table())
print("snippets(model):")
print(pdf.snippets("model", max_results=2, ignore_case=true))
print("read(pages=[1]):")
print(pdf.read(pages=[1]))

print("=== DOCX TEST ===")
docx = File("data/office_samples/project_status_report.docx")
print("contains(project):", docx.contains("project", ignore_case=true))
print("search(project):", docx.search("project", ignore_case=true))
print("head_len:", len(docx.head()))
print("tail_len:", len(docx.tail()))
print("table:")
print(docx.table())
print("snippets(project):")
print(docx.snippets("project", max_results=2, ignore_case=true))
print("read(pages=[1,2]):")
print(docx.read(pages=[1, 2]))

print("=== PPTX TEST ===")
pptx = File("data/office_samples/project_kickoff_deck.pptx")
print("contains(project):", pptx.contains("project", ignore_case=true))
print("search(project):", pptx.search("project", ignore_case=true))
print("head_len:", len(pptx.head()))
print("tail_len:", len(pptx.tail()))
print("table:")
print(pptx.table())
print("snippets(project):")
print(pptx.snippets("project", max_results=2, ignore_case=true))
print("read(pages=[1,3]):")
print(pptx.read(pages=[1, 3]))
"""

history = execute_fdsl(code, cwd=".", sandbox_root=".")
print(history)
